<?php

namespace DHelper\Libs\Tree;

class RedBlackTree extends BinarySearchTree
{
    protected function createNode($value, Node $node = null)
    {
        return new class($value, $node) extends Node
        {
            /**
             * 是否为红色
             * @var bool
             */
            protected $isRed = true;

            public function __construct($value, Node $node = null)
            {
                $this->setValue($value);
                if ($node) {
                    $this->setParentNode($node);
                }
            }
        };
    }

    protected function _insert($value): bool
    {
        return parent::_insert($value);
    }

    protected function _delete($value)
    {
        return parent::_delete($value); // TODO: Change the autogenerated stub
    }

    public function leftRotate()
    {
        return parent::leftRotate(); // TODO: Change the autogenerated stub
    }

    public function rightRotate()
    {
        return parent::rightRotate(); // TODO: Change the autogenerated stub
    }

}